import { Geist, Geist_Mono, Playfair_Display_SC  } from "next/font/google";
import "./globals.css";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#fca5a5" }, // red-300
    { media: "(min-width: 1024px)", color: "#b91c1c" }, // red-700-ish
    { media: "(min-width: 1536px)", color: "#22c55e" }, // green-500-ish
  ],
};

// app/layout.js
export const viewport = {
  width: "device-width",
  initialScale: 1,
};


export default function RootLayout({ children }) {
  return (
   <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} antialiased bg-transparent`}
      >
        {children}
      </body>
    </html>
  );
}
